#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.7

pipelines:
  default:
    - parallel:
      - step:
          name: Run Rspec
          script:
	    - gem install bundler -v 1.17.2
            - bundle install
            - bundle exec rspec
